
spring:
  application:
    name: gateway-service
server:
  port: ${PORT:8080}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:87861}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80


zuul:
  prefix: /api
  routes:
    chucknorris:
      path: /chucknorris/**
      serviceId: chucknorris-service
