
spring:
  application:
    name: gateway-service
server:
  port: ${PORT:8080}

zuul:
  prefix: /api
  routes:
    chucknorris:
      path: /chucknorris/**
      serviceId: chucknorris-service
    tours:
      path: /tour/**
      serviceId: tours-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/

